/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package net.gumbercules.loot;

public final class R {
    public static final class array {
        public static final int repeat=0x7f040000;
        public static final int sort=0x7f040001;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int ic_menu_today=0x7f020000;
        public static final int icon=0x7f020001;
    }
    public static final class id {
        public static final int AccountBalance=0x7f06000b;
        public static final int AccountName=0x7f06000a;
        public static final int ActualRadio=0x7f060035;
        public static final int AmountText=0x7f06003c;
        public static final int BalText1=0x7f060010;
        public static final int BalText2=0x7f060013;
        public static final int BalText3=0x7f060016;
        public static final int BalanceEdit=0x7f060006;
        public static final int BalanceLabel=0x7f060005;
        public static final int BalanceLayout=0x7f06000f;
        public static final int BalanceRow=0x7f060004;
        public static final int BudgetRadio=0x7f060036;
        public static final int CancelButton=0x7f060009;
        public static final int ClearButton=0x7f06000e;
        public static final int DateText=0x7f06003b;
        public static final int LinearLayout01=0x7f060007;
        public static final int LinearLayout02=0x7f060012;
        public static final int LinearLayout03=0x7f060015;
        public static final int NameEdit=0x7f060003;
        public static final int NameLabel=0x7f060002;
        public static final int NameRow=0x7f060001;
        public static final int PartyText=0x7f06003a;
        public static final int PostedCheckBox=0x7f060039;
        public static final int RadioGroup01=0x7f060019;
        public static final int RadioGroup02=0x7f060034;
        public static final int SaveButton=0x7f060008;
        public static final int ScrollView01=0x7f060018;
        public static final int SearchEdit=0x7f06000d;
        public static final int SearchLayout=0x7f06000c;
        public static final int TableLayout01=0x7f060000;
        public static final int accountLabel=0x7f060028;
        public static final int accountRow=0x7f060027;
        public static final int accountSpinner=0x7f060029;
        public static final int amountEdit=0x7f060023;
        public static final int amountLabel=0x7f060022;
        public static final int amountRow=0x7f060021;
        public static final int balanceValue=0x7f060014;
        public static final int budgetRow=0x7f060033;
        public static final int budgetValue=0x7f060017;
        public static final int cancelButton=0x7f060038;
        public static final int checkEdit=0x7f06002c;
        public static final int checkLabel=0x7f06002b;
        public static final int checkRadio=0x7f06001c;
        public static final int checkRow=0x7f06002a;
        public static final int dateEdit=0x7f06001f;
        public static final int dateLabel=0x7f06001e;
        public static final int datePickerButton=0x7f060020;
        public static final int dateRow=0x7f06001d;
        public static final int depositRadio=0x7f06001b;
        public static final int partyEdit=0x7f060026;
        public static final int partyLabel=0x7f060025;
        public static final int partyRow=0x7f060024;
        public static final int postedValue=0x7f060011;
        public static final int repeatLabel=0x7f060031;
        public static final int repeatRow=0x7f060030;
        public static final int repeatSpinner=0x7f060032;
        public static final int saveButton=0x7f060037;
        public static final int tagsEdit=0x7f06002f;
        public static final int tagsLabel=0x7f06002e;
        public static final int tagsRow=0x7f06002d;
        public static final int withdrawRadio=0x7f06001a;
    }
    public static final class layout {
        public static final int account_edit=0x7f030000;
        public static final int account_row=0x7f030001;
        public static final int accounts=0x7f030002;
        public static final int main=0x7f030003;
        public static final int options=0x7f030004;
        public static final int trans=0x7f030005;
        public static final int trans_row_narrow=0x7f030006;
        public static final int trans_row_wide=0x7f030007;
    }
    public static final class string {
        public static final int account_del_box=0x7f050011;
        public static final int acct_bal=0x7f05000a;
        public static final int acct_name=0x7f050009;
        public static final int app_name=0x7f050000;
        public static final int cancel=0x7f05000c;
        public static final int copy=0x7f050012;
        public static final int del=0x7f05000e;
        public static final int edit=0x7f05000d;
        public static final int new_account=0x7f050008;
        public static final int new_trans=0x7f050002;
        public static final int no=0x7f050010;
        public static final int purge=0x7f050007;
        public static final int save=0x7f05000b;
        public static final int search=0x7f050006;
        public static final int search_text=0x7f050001;
        public static final int settings=0x7f050003;
        public static final int sort=0x7f050005;
        public static final int sort_column=0x7f050016;
        public static final int trans_balance=0x7f050015;
        public static final int trans_budget=0x7f050014;
        public static final int trans_posted=0x7f050013;
        public static final int transfer=0x7f050004;
        public static final int yes=0x7f05000f;
    }
}
