/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package net.gumbercules.loot;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int icon=0x7f020000;
    }
    public static final class id {
        public static final int AmountText=0x7f05002a;
        public static final int BalText1=0x7f050001;
        public static final int BalText2=0x7f050002;
        public static final int BalText3=0x7f050003;
        public static final int BalanceLayout=0x7f050000;
        public static final int BalanceText=0x7f05002d;
        public static final int Button01=0x7f050024;
        public static final int Button02=0x7f050025;
        public static final int CheckRadio=0x7f050009;
        public static final int DateText=0x7f05002c;
        public static final int DepositRadio=0x7f050007;
        public static final int EditText01=0x7f05000e;
        public static final int EditText02=0x7f050012;
        public static final int EditText03=0x7f050015;
        public static final int EditText04=0x7f050018;
        public static final int EditText05=0x7f05001b;
        public static final int IdText=0x7f050027;
        public static final int ImageButton01=0x7f05000f;
        public static final int LinearLayout01=0x7f050005;
        public static final int LinearLayout02=0x7f05000d;
        public static final int LinearLayout03=0x7f050023;
        public static final int PartyText=0x7f050029;
        public static final int PostedCheckBox=0x7f050028;
        public static final int RadioButton04=0x7f050021;
        public static final int RadioButton05=0x7f050022;
        public static final int RadioGroup01=0x7f050006;
        public static final int RadioGroup02=0x7f050020;
        public static final int ScrollView01=0x7f050004;
        public static final int Spinner01=0x7f05001e;
        public static final int TableLayout01=0x7f05000a;
        public static final int TableRow01=0x7f05000b;
        public static final int TableRow02=0x7f050010;
        public static final int TableRow03=0x7f050013;
        public static final int TableRow04=0x7f050016;
        public static final int TableRow05=0x7f050019;
        public static final int TableRow06=0x7f05001c;
        public static final int TableRow07=0x7f05001f;
        public static final int TextView01=0x7f05000c;
        public static final int TextView02=0x7f050011;
        public static final int TextView03=0x7f050014;
        public static final int TextView04=0x7f050017;
        public static final int TextView05=0x7f05001a;
        public static final int TextView06=0x7f05001d;
        public static final int TransactionRowLandscape=0x7f05002b;
        public static final int TransactionRowPortrait=0x7f050026;
        public static final int WithdrawRadio=0x7f050008;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int options=0x7f030001;
        public static final int trans=0x7f030002;
        public static final int trans_row_narrow=0x7f030003;
        public static final int trans_row_wide=0x7f030004;
    }
    public static final class string {
        public static final int app_name=0x7f040000;
        public static final int search_text=0x7f040001;
    }
}
